name: rustnithm_server
description: A Rust-powered server for Rustnithm
publish_to: 'none'

version: 8.1.0+364

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  url_launcher: ^6.3.2
  flutter_rust_bridge: 2.12.0
  network_info_plus: ^8.1.0
  window_manager: ^0.5.1
  ffi: ^2.2.0
  flutter_acrylic: ^1.1.4

  meta: ^1.17.0
  uuid: ^4.5.3
  collection: ^1.19.1
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^21.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/app.png"
    icon_size: 255

flutter:
  uses-material-design: true

  assets:
    - assets/app.png
    - assets/banner.png
