// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class RustnithmNative {
  Stream<SensorData> createSensorStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateSensorStreamConstMeta;

  Stream<LogEntry> createLogStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateLogStreamConstMeta;

  Future<String> startServer(
      {required int port, required bool isUdp, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStartServerConstMeta;

  Future<bool> stopServer({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStopServerConstMeta;

  Future<void> sendLog(
      {required String level, required String message, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSendLogConstMeta;

  Future<void> reportToFlutter(
      {required Uint8List air,
      required Uint8List slider,
      required int coin,
      required int service,
      required int test,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReportToFlutterConstMeta;

  Future<void> syncToShmem(
      {required Uint8List air,
      required Uint8List slider,
      required int coin,
      required int service,
      required int test,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSyncToShmemConstMeta;
}

class LogEntry {
  final String time;
  final String level;
  final String message;

  const LogEntry({
    required this.time,
    required this.level,
    required this.message,
  });
}

class SensorData {
  final Uint8List air;
  final Uint8List slider;
  final int coin;
  final int service;
  final int test;

  const SensorData({
    required this.air,
    required this.slider,
    required this.coin,
    required this.service,
    required this.test,
  });
}

class RustnithmNativeImpl implements RustnithmNative {
  final RustnithmNativePlatform _platform;
  factory RustnithmNativeImpl(ExternalLibrary dylib) =>
      RustnithmNativeImpl.raw(RustnithmNativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory RustnithmNativeImpl.wasm(FutureOr<WasmModule> module) =>
      RustnithmNativeImpl(module as ExternalLibrary);
  RustnithmNativeImpl.raw(this._platform);
  Stream<SensorData> createSensorStream({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_create_sensor_stream(port_),
      parseSuccessData: _wire2api_sensor_data,
      parseErrorData: null,
      constMeta: kCreateSensorStreamConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCreateSensorStreamConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_sensor_stream",
        argNames: [],
      );

  Stream<LogEntry> createLogStream({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_create_log_stream(port_),
      parseSuccessData: _wire2api_log_entry,
      parseErrorData: null,
      constMeta: kCreateLogStreamConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCreateLogStreamConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_log_stream",
        argNames: [],
      );

  Future<String> startServer(
      {required int port, required bool isUdp, dynamic hint}) {
    var arg0 = api2wire_u16(port);
    var arg1 = isUdp;
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_start_server(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kStartServerConstMeta,
      argValues: [port, isUdp],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStartServerConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "start_server",
        argNames: ["port", "isUdp"],
      );

  Future<bool> stopServer({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_stop_server(port_),
      parseSuccessData: _wire2api_bool,
      parseErrorData: null,
      constMeta: kStopServerConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStopServerConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "stop_server",
        argNames: [],
      );

  Future<void> sendLog(
      {required String level, required String message, dynamic hint}) {
    var arg0 = _platform.api2wire_String(level);
    var arg1 = _platform.api2wire_String(message);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_send_log(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      parseErrorData: null,
      constMeta: kSendLogConstMeta,
      argValues: [level, message],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSendLogConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "send_log",
        argNames: ["level", "message"],
      );

  Future<void> reportToFlutter(
      {required Uint8List air,
      required Uint8List slider,
      required int coin,
      required int service,
      required int test,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(air);
    var arg1 = _platform.api2wire_uint_8_list(slider);
    var arg2 = api2wire_u8(coin);
    var arg3 = api2wire_u8(service);
    var arg4 = api2wire_u8(test);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_report_to_flutter(port_, arg0, arg1, arg2, arg3, arg4),
      parseSuccessData: _wire2api_unit,
      parseErrorData: null,
      constMeta: kReportToFlutterConstMeta,
      argValues: [air, slider, coin, service, test],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kReportToFlutterConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "report_to_flutter",
        argNames: ["air", "slider", "coin", "service", "test"],
      );

  Future<void> syncToShmem(
      {required Uint8List air,
      required Uint8List slider,
      required int coin,
      required int service,
      required int test,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(air);
    var arg1 = _platform.api2wire_uint_8_list(slider);
    var arg2 = api2wire_u8(coin);
    var arg3 = api2wire_u8(service);
    var arg4 = api2wire_u8(test);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_sync_to_shmem(port_, arg0, arg1, arg2, arg3, arg4),
      parseSuccessData: _wire2api_unit,
      parseErrorData: null,
      constMeta: kSyncToShmemConstMeta,
      argValues: [air, slider, coin, service, test],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSyncToShmemConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sync_to_shmem",
        argNames: ["air", "slider", "coin", "service", "test"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  LogEntry _wire2api_log_entry(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LogEntry(
      time: _wire2api_String(arr[0]),
      level: _wire2api_String(arr[1]),
      message: _wire2api_String(arr[2]),
    );
  }

  SensorData _wire2api_sensor_data(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SensorData(
      air: _wire2api_uint_8_list(arr[0]),
      slider: _wire2api_uint_8_list(arr[1]),
      coin: _wire2api_u8(arr[2]),
      service: _wire2api_u8(arr[3]),
      test: _wire2api_u8(arr[4]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
bool api2wire_bool(bool raw) {
  return raw;
}

@protected
int api2wire_u16(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class RustnithmNativePlatform
    extends FlutterRustBridgeBase<RustnithmNativeWire> {
  RustnithmNativePlatform(ffi.DynamicLibrary dylib)
      : super(RustnithmNativeWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustnithmNativeWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustnithmNativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustnithmNativeWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(int ptr) {
    return _get_dart_object(ptr);
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
    'get_dart_object',
  );
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(int ptr) {
    return _drop_dart_object(ptr);
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
    'drop_dart_object',
  );
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(Object handle) {
    return _new_dart_opaque(handle);
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
    'new_dart_opaque',
  );
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(ffi.Pointer<ffi.Void> obj) {
    return _init_frb_dart_api_dl(obj);
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
    'init_frb_dart_api_dl',
  );
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_create_sensor_stream(int port_) {
    return _wire_create_sensor_stream(port_);
  }

  late final _wire_create_sensor_streamPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'wire_create_sensor_stream',
  );
  late final _wire_create_sensor_stream =
      _wire_create_sensor_streamPtr.asFunction<void Function(int)>();

  void wire_create_log_stream(int port_) {
    return _wire_create_log_stream(port_);
  }

  late final _wire_create_log_streamPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'wire_create_log_stream',
  );
  late final _wire_create_log_stream =
      _wire_create_log_streamPtr.asFunction<void Function(int)>();

  void wire_start_server(int port_, int port, bool is_udp) {
    return _wire_start_server(port_, port, is_udp);
  }

  late final _wire_start_serverPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint16, ffi.Bool)>>(
      'wire_start_server');
  late final _wire_start_server =
      _wire_start_serverPtr.asFunction<void Function(int, int, bool)>();

  void wire_stop_server(int port_) {
    return _wire_stop_server(port_);
  }

  late final _wire_stop_serverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'wire_stop_server',
  );
  late final _wire_stop_server =
      _wire_stop_serverPtr.asFunction<void Function(int)>();

  void wire_send_log(
    int port_,
    ffi.Pointer<wire_uint_8_list> level,
    ffi.Pointer<wire_uint_8_list> message,
  ) {
    return _wire_send_log(port_, level, message);
  }

  late final _wire_send_logPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
          )>>('wire_send_log');
  late final _wire_send_log = _wire_send_logPtr.asFunction<
      void Function(
        int,
        ffi.Pointer<wire_uint_8_list>,
        ffi.Pointer<wire_uint_8_list>,
      )>();

  void wire_report_to_flutter(
    int port_,
    ffi.Pointer<wire_uint_8_list> air,
    ffi.Pointer<wire_uint_8_list> slider,
    int coin,
    int service,
    int test,
  ) {
    return _wire_report_to_flutter(port_, air, slider, coin, service, test);
  }

  late final _wire_report_to_flutterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Uint8,
            ffi.Uint8,
            ffi.Uint8,
          )>>('wire_report_to_flutter');
  late final _wire_report_to_flutter = _wire_report_to_flutterPtr.asFunction<
      void Function(
        int,
        ffi.Pointer<wire_uint_8_list>,
        ffi.Pointer<wire_uint_8_list>,
        int,
        int,
        int,
      )>();

  void wire_sync_to_shmem(
    int port_,
    ffi.Pointer<wire_uint_8_list> air,
    ffi.Pointer<wire_uint_8_list> slider,
    int coin,
    int service,
    int test,
  ) {
    return _wire_sync_to_shmem(port_, air, slider, coin, service, test);
  }

  late final _wire_sync_to_shmemPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Pointer<wire_uint_8_list>,
            ffi.Uint8,
            ffi.Uint8,
            ffi.Uint8,
          )>>('wire_sync_to_shmem');
  late final _wire_sync_to_shmem = _wire_sync_to_shmemPtr.asFunction<
      void Function(
        int,
        ffi.Pointer<wire_uint_8_list>,
        ffi.Pointer<wire_uint_8_list>,
        int,
        int,
        int,
      )>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(int len) {
    return _new_uint_8_list_0(len);
  }

  late final _new_uint_8_list_0Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>(
      'new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(WireSyncReturn ptr) {
    return _free_WireSyncReturn(ptr);
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
    'free_WireSyncReturn',
  );
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
