#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_create_sensor_stream_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "create_sensor_stream",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            move |task_callback| {
                Result::<_, ()>::Ok(create_sensor_stream(
                    task_callback.stream_sink::<_, SensorData>(),
                ))
            }
        },
    )
}
fn wire_create_log_stream_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "create_log_stream",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            move |task_callback| {
                Result::<_, ()>::Ok(create_log_stream(
                    task_callback.stream_sink::<_, LogEntry>(),
                ))
            }
        },
    )
}
fn wire_start_server_impl(
    port_: MessagePort,
    port: impl Wire2Api<u16> + UnwindSafe,
    is_udp: impl Wire2Api<bool> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "start_server",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_port = port.wire2api();
            let api_is_udp = is_udp.wire2api();
            move |task_callback| Result::<_, ()>::Ok(start_server(api_port, api_is_udp))
        },
    )
}
fn wire_stop_server_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "stop_server",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Result::<_, ()>::Ok(stop_server()),
    )
}
fn wire_send_log_impl(
    port_: MessagePort,
    level: impl Wire2Api<String> + UnwindSafe,
    message: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "send_log",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_level = level.wire2api();
            let api_message = message.wire2api();
            move |task_callback| Result::<_, ()>::Ok(send_log(api_level, api_message))
        },
    )
}
fn wire_report_to_flutter_impl(
    port_: MessagePort,
    air: impl Wire2Api<Vec<u8>> + UnwindSafe,
    slider: impl Wire2Api<Vec<u8>> + UnwindSafe,
    coin: impl Wire2Api<u8> + UnwindSafe,
    service: impl Wire2Api<u8> + UnwindSafe,
    test: impl Wire2Api<u8> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "report_to_flutter",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_air = air.wire2api();
            let api_slider = slider.wire2api();
            let api_coin = coin.wire2api();
            let api_service = service.wire2api();
            let api_test = test.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(report_to_flutter(
                    api_air,
                    api_slider,
                    api_coin,
                    api_service,
                    api_test,
                ))
            }
        },
    )
}
fn wire_sync_to_shmem_impl(
    port_: MessagePort,
    air: impl Wire2Api<Vec<u8>> + UnwindSafe,
    slider: impl Wire2Api<Vec<u8>> + UnwindSafe,
    coin: impl Wire2Api<u8> + UnwindSafe,
    service: impl Wire2Api<u8> + UnwindSafe,
    test: impl Wire2Api<u8> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "sync_to_shmem",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_air = air.wire2api();
            let api_slider = slider.wire2api();
            let api_coin = coin.wire2api();
            let api_service = service.wire2api();
            let api_test = test.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(sync_to_shmem(
                    api_air,
                    api_slider,
                    api_coin,
                    api_service,
                    api_test,
                ))
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}
impl Wire2Api<u16> for u16 {
    fn wire2api(self) -> u16 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for LogEntry {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.time.into_into_dart().into_dart(),
            self.level.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LogEntry {}
impl rust2dart::IntoIntoDart<LogEntry> for LogEntry {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for SensorData {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.air.into_into_dart().into_dart(),
            self.slider.into_into_dart().into_dart(),
            self.coin.into_into_dart().into_dart(),
            self.service.into_into_dart().into_dart(),
            self.test.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for SensorData {}
impl rust2dart::IntoIntoDart<SensorData> for SensorData {
    fn into_into_dart(self) -> Self {
        self
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use self::io::*;
